version: 0.2
env:
    secrets-manager:
        TOKEN: SonarCloud:sonarCloudToken
phases:
  install:
    runtime-versions:
      java: latest
  build:
    commands:
      - mvn verify sonar:sonar -Dsonar.projectKey=awsdevsecops-vijay_awsdevsecops -Dsonar.organization=awsdevsecops-vijay -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=$TOKEN 
